USE ROY;

SET FOREIGN_KEY_CHECKS = 0;

-- Tablas que dependen de otras (hijas) primero:
TRUNCATE TABLE FAVORITO;
TRUNCATE TABLE MENSAJE;
TRUNCATE TABLE NOTIFICACION;
TRUNCATE TABLE REPORTE;
TRUNCATE TABLE IMAGEN_OBJETO;
TRUNCATE TABLE TRANSACCION;
TRUNCATE TABLE SOLICITUD_RENTA;
TRUNCATE TABLE RESENA;
TRUNCATE TABLE CUENTABANCARIA;

-- Tablas base (padres) al final:
TRUNCATE TABLE OBJETO;
TRUNCATE TABLE USUARIO;

SET FOREIGN_KEY_CHECKS = 1;


SELECT id_usuario, nombre_us, foto_url, zona
FROM usuario
WHERE id_usuario = 1;

